[package]
name = "cloud-run-with-rust-sample"
version = "0.1.0"
edition = "2021"
authors = ["harrythecode"]
description = "Cloud Run with Rust Sample - Rust Cloud Run service with Axum"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
